// pages/index.js

import Head from "next/head";
import Link from "next/link";
import Navlinks from "../components/Naavlinks";

//
const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="container">
          <div className="row">
            <div className="col-2 mt-5">
              <Navlinks />
            </div>

            <div className="col-10 mt-5">
              <h1>Data editor</h1>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
